name: rive
version: 1.0.0
homepage: https://rive.app
description: Rive 2 Flutter Runtime. This package provides runtime functionality for playing back and interacting with animations built with the Rive editor available at https://rive.app.
repository: https://github.com/rive-app/rive-flutter
topics:
  - animation
  - ui
  - effects
  - widgets
  - widget
environment:
  sdk: '>=2.14.0 <4.0.0'
  flutter: '>=2.5.0'
dependencies:
  collection: ^1.17.2
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^1.0.0
  meta: ^1.9.1
  plugin_platform_interface: ^2.1.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail:
  path: ^1.8.3
